import {
  School,
  Cooperative,
  Role,
  User,
  Category,
  Unit,
  Supplier,
  Product,
  ProductBatch,
  StockMovement,
  AppSettings,
  CashSession,
} from '../domain/types';
import {
  STORES,
  getFromStore,
  putToStore,
  putMultipleToStore,
} from '../repositories/indexeddb/db';

export const DEFAULT_SCHOOL_ID = 'sch_sdn_mandiri_01';

export async function initializeSeedData(): Promise<void> {
  const existingSchool = await getFromStore<School>(STORES.SCHOOLS, DEFAULT_SCHOOL_ID);
  if (existingSchool) {
    // Already initialized
    return;
  }

  const now = new Date().toISOString();
  const today = now.slice(0, 10);

  // 1. School & Cooperative
  const defaultSchool: School = {
    id: DEFAULT_SCHOOL_ID,
    school_name: 'SD Negeri Mandiri 01',
    npsn: '20109988',
    address: 'Jl. Pendidikan No. 45, Jakarta Selatan',
    phone: '021-7890123',
    email: 'koperasi@sdnmandiri01.sch.id',
    logo: '',
    status: 'Active',
    created_at: now,
  };
  await putToStore(STORES.SCHOOLS, defaultSchool);

  const defaultCooperative: Cooperative = {
    id: 'coop_mandiri_01',
    school_id: DEFAULT_SCHOOL_ID,
    cooperative_name: 'Koperasi Sekolah Berkah Mandiri',
    established_date: '2020-01-15',
    description: 'Koperasi Sekolah melayani kebutuhan alat tulis, seragam, dan makanan sehat siswa & guru.',
  };
  await putToStore(STORES.COOPERATIVES, defaultCooperative);

  // 2. Settings
  const defaultSettings: AppSettings = {
    id: 'set_mandiri_01',
    school_id: DEFAULT_SCHOOL_ID,
    hpp_method: 'FIFO',
    default_min_stock: 5,
    currency: 'IDR',
    receipt_header: 'KOPERASI SEKOLAH BERKAH MANDIRI\nSD NEGERI MANDIRI 01\nJl. Pendidikan No. 45',
    receipt_footer: 'Terima kasih atas kunjungan Anda!\nBarang yang sudah dibeli tidak dapat ditukar kecuali cacat produksi.',
    auto_print: false,
    enable_expiry_warning: true,
    enable_batches: true,
    updated_at: now,
  };
  await putToStore(STORES.SETTINGS, defaultSettings);

  // 3. Roles
  const roles: Role[] = [
    { id: 'role_admin', role_name: 'Administrator', description: 'Akses penuh seluruh modul, konfigurasi & backup', created_at: now },
    { id: 'role_ketua', role_name: 'Ketua', description: 'Pengawas operasional, dashboard eksekutif & persetujuan', created_at: now },
    { id: 'role_bendahara', role_name: 'Bendahara', description: 'Pengelola arus kas, keuangan, dan laporan laba', created_at: now },
    { id: 'role_pengurus', role_name: 'Pengurus', description: 'Pengelola master barang, pembelian, dan persediaan', created_at: now },
    { id: 'role_kasir', role_name: 'Kasir', description: 'Operasional penjualan harian dan struk', created_at: now },
    { id: 'role_viewer', role_name: 'Viewer', description: 'Akses baca untuk guru & kepala sekolah', created_at: now },
  ];
  await putMultipleToStore(STORES.ROLES, roles);

  // 4. Users (Password hash placeholder for offline simulation)
  const users: User[] = [
    {
      id: 'usr_admin',
      school_id: DEFAULT_SCHOOL_ID,
      full_name: 'Budi Santoso, S.Kom',
      username: 'admin',
      password_hash: 'sha256_mock_admin',
      role_id: 'role_admin',
      role_name: 'Administrator',
      phone: '081234567890',
      email: 'admin@sdnmandiri01.sch.id',
      status: 'Active',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'usr_ketua',
      school_id: DEFAULT_SCHOOL_ID,
      full_name: 'Dra. Hj. Nurhayati, M.Pd',
      username: 'ketua',
      password_hash: 'sha256_mock_ketua',
      role_id: 'role_ketua',
      role_name: 'Ketua',
      phone: '081298765432',
      email: 'nurhayati@sdnmandiri01.sch.id',
      status: 'Active',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'usr_bendahara',
      school_id: DEFAULT_SCHOOL_ID,
      full_name: 'Siti Rahmawati, S.E.',
      username: 'bendahara',
      password_hash: 'sha256_mock_bendahara',
      role_id: 'role_bendahara',
      role_name: 'Bendahara',
      phone: '081345678901',
      email: 'bendahara@sdnmandiri01.sch.id',
      status: 'Active',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'usr_pengurus',
      school_id: DEFAULT_SCHOOL_ID,
      full_name: 'Ahmad Fauzi, S.Pd',
      username: 'pengurus',
      password_hash: 'sha256_mock_pengurus',
      role_id: 'role_pengurus',
      role_name: 'Pengurus',
      phone: '081567890123',
      email: 'fauzi@sdnmandiri01.sch.id',
      status: 'Active',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'usr_kasir',
      school_id: DEFAULT_SCHOOL_ID,
      full_name: 'Dewi Anggraini (Petugas Kasir)',
      username: 'kasir',
      password_hash: 'sha256_mock_kasir',
      role_id: 'role_kasir',
      role_name: 'Kasir',
      phone: '081789012345',
      email: 'kasir@sdnmandiri01.sch.id',
      status: 'Active',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'usr_viewer',
      school_id: DEFAULT_SCHOOL_ID,
      full_name: 'Drs. H. Mulyadi (Kepala Sekolah)',
      username: 'kepsek',
      password_hash: 'sha256_mock_viewer',
      role_id: 'role_viewer',
      role_name: 'Viewer',
      phone: '081890123456',
      email: 'kepsek@sdnmandiri01.sch.id',
      status: 'Active',
      created_at: now,
      updated_at: now,
    },
  ];
  await putMultipleToStore(STORES.USERS, users);

  // 5. Categories
  const categories: Category[] = [
    { id: 'cat_atk', school_id: DEFAULT_SCHOOL_ID, name: 'Alat Tulis Kantor & Sekolah', code: 'ATK', sort_order: 1, status: 'Active', created_at: now },
    { id: 'cat_snack', school_id: DEFAULT_SCHOOL_ID, name: 'Makanan & Snack Sehat', code: 'SNCK', sort_order: 2, status: 'Active', created_at: now },
    { id: 'cat_drink', school_id: DEFAULT_SCHOOL_ID, name: 'Minuman Dingin & Hangat', code: 'DRK', sort_order: 3, status: 'Active', created_at: now },
    { id: 'cat_uniform', school_id: DEFAULT_SCHOOL_ID, name: 'Seragam & Atribut Sekolah', code: 'SRG', sort_order: 4, status: 'Active', created_at: now },
    { id: 'cat_books', school_id: DEFAULT_SCHOOL_ID, name: 'Buku Pelajaran & Tulis', code: 'BKU', sort_order: 5, status: 'Active', created_at: now },
  ];
  await putMultipleToStore(STORES.CATEGORIES, categories);

  // 6. Units
  const units: Unit[] = [
    { id: 'unit_pcs', school_id: DEFAULT_SCHOOL_ID, name: 'Pcs / Buah', code: 'PCS', created_at: now },
    { id: 'unit_pack', school_id: DEFAULT_SCHOOL_ID, name: 'Pack / Kotak', code: 'PAK', created_at: now },
    { id: 'unit_bottle', school_id: DEFAULT_SCHOOL_ID, name: 'Botol', code: 'BTL', created_at: now },
    { id: 'unit_set', school_id: DEFAULT_SCHOOL_ID, name: 'Set', code: 'SET', created_at: now },
    { id: 'unit_book', school_id: DEFAULT_SCHOOL_ID, name: 'Buku', code: 'BKU', created_at: now },
  ];
  await putMultipleToStore(STORES.UNITS, units);

  // 7. Suppliers
  const suppliers: Supplier[] = [
    {
      id: 'sup_gramedia',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'SUP-001',
      name: 'PT Mitra Edukasi ATK',
      contact_person: 'Pak Hendra',
      phone: '081299887766',
      email: 'sales@mitraatk.co.id',
      address: 'Kawasan Niaga Pulogadung Blok C No. 12',
      total_debt: 0,
      status: 'Active',
      created_at: now,
    },
    {
      id: 'sup_distributor_snack',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'SUP-002',
      name: 'CV Berkah Pangan Mandiri',
      contact_person: 'Ibu Rina',
      phone: '081377889900',
      email: 'rina@berkahpangan.com',
      address: 'Jl. Raya Pasar Minggu No. 88',
      total_debt: 0,
      status: 'Active',
      created_at: now,
    },
    {
      id: 'sup_konveksi_seragam',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'SUP-003',
      name: 'Grosir Seragam Sekolah Jaya',
      contact_person: 'Pak Slamet',
      phone: '081512348899',
      email: 'seragamjaya@gmail.com',
      address: 'Pusat Grosir Tanah Abang Lt. 2 Blok F',
      total_debt: 0,
      status: 'Active',
      created_at: now,
    },
  ];
  await putMultipleToStore(STORES.SUPPLIERS, suppliers);

  // 8. Products & Batches
  const products: Product[] = [
    {
      id: 'prd_01',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'ATK-001',
      name: 'Buku Tulis Sinar Dunia 38 Lembar',
      category_id: 'cat_books',
      unit_id: 'unit_book',
      selling_price: 4500,
      min_stock: 10,
      has_expiry: false,
      status: 'Active',
      total_stock: 45,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'prd_02',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'ATK-002',
      name: 'Pulpen Standard AE7 0.5mm Hitam',
      category_id: 'cat_atk',
      unit_id: 'unit_pcs',
      selling_price: 3000,
      min_stock: 15,
      has_expiry: false,
      status: 'Active',
      total_stock: 60,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'prd_03',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'ATK-003',
      name: 'Pensil 2B Faber-Castell Ujian Asli',
      category_id: 'cat_atk',
      unit_id: 'unit_pcs',
      selling_price: 4000,
      min_stock: 10,
      has_expiry: false,
      status: 'Active',
      total_stock: 35,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'prd_04',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'ATK-004',
      name: 'Penghapus Pensil Joyko Putih EB-30',
      category_id: 'cat_atk',
      unit_id: 'unit_pcs',
      selling_price: 2000,
      min_stock: 8,
      has_expiry: false,
      status: 'Active',
      total_stock: 25,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'prd_05',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'ATK-005',
      name: 'Penggaris Mika Bening Butterfly 30cm',
      category_id: 'cat_atk',
      unit_id: 'unit_pcs',
      selling_price: 3500,
      min_stock: 5,
      has_expiry: false,
      status: 'Active',
      total_stock: 18,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'prd_06',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'DRK-001',
      name: 'Susu Ultra Milk Cokelat 200ml',
      category_id: 'cat_drink',
      unit_id: 'unit_bottle',
      selling_price: 6000,
      min_stock: 10,
      has_expiry: true,
      status: 'Active',
      total_stock: 24,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'prd_07',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'DRK-002',
      name: 'Teh Pucuk Harum Melati 350ml',
      category_id: 'cat_drink',
      unit_id: 'unit_bottle',
      selling_price: 4000,
      min_stock: 12,
      has_expiry: true,
      status: 'Active',
      total_stock: 30,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'prd_08',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'SNC-001',
      name: 'Biskuit Roma Kelapa 300g',
      category_id: 'cat_snack',
      unit_id: 'unit_pack',
      selling_price: 9500,
      min_stock: 6,
      has_expiry: true,
      status: 'Active',
      total_stock: 12,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'prd_09',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'SRG-001',
      name: 'Seragam Merah Putih SD Lengan Pendek No. 4',
      category_id: 'cat_uniform',
      unit_id: 'unit_pcs',
      selling_price: 65000,
      min_stock: 4,
      has_expiry: false,
      status: 'Active',
      total_stock: 8,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'prd_10',
      school_id: DEFAULT_SCHOOL_ID,
      code: 'SRG-002',
      name: 'Dasi Merah SD & Topi Tut Wuri Handayani (Set)',
      category_id: 'cat_uniform',
      unit_id: 'unit_set',
      selling_price: 25000,
      min_stock: 5,
      has_expiry: false,
      status: 'Active',
      total_stock: 15,
      created_at: now,
      updated_at: now,
    },
  ];
  await putMultipleToStore(STORES.PRODUCTS, products);

  // 9. Initial Product Batches (For FIFO tracking)
  const batches: ProductBatch[] = [
    {
      id: 'btc_01_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_01',
      batch_number: 'BCH-2026-001',
      purchase_price: 3300,
      initial_qty: 45,
      remaining_qty: 45,
      supplier_id: 'sup_gramedia',
      status: 'Aktif',
      created_at: now,
    },
    {
      id: 'btc_02_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_02',
      batch_number: 'BCH-2026-002',
      purchase_price: 2100,
      initial_qty: 60,
      remaining_qty: 60,
      supplier_id: 'sup_gramedia',
      status: 'Aktif',
      created_at: now,
    },
    {
      id: 'btc_03_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_03',
      batch_number: 'BCH-2026-003',
      purchase_price: 2800,
      initial_qty: 35,
      remaining_qty: 35,
      supplier_id: 'sup_gramedia',
      status: 'Aktif',
      created_at: now,
    },
    {
      id: 'btc_04_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_04',
      batch_number: 'BCH-2026-004',
      purchase_price: 1200,
      initial_qty: 25,
      remaining_qty: 25,
      supplier_id: 'sup_gramedia',
      status: 'Aktif',
      created_at: now,
    },
    {
      id: 'btc_05_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_05',
      batch_number: 'BCH-2026-005',
      purchase_price: 2400,
      initial_qty: 18,
      remaining_qty: 18,
      supplier_id: 'sup_gramedia',
      status: 'Aktif',
      created_at: now,
    },
    {
      id: 'btc_06_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_06',
      batch_number: 'BCH-2026-006',
      purchase_price: 4800,
      initial_qty: 24,
      remaining_qty: 24,
      supplier_id: 'sup_distributor_snack',
      expiry_date: '2026-11-20',
      status: 'Aktif',
      created_at: now,
    },
    {
      id: 'btc_07_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_07',
      batch_number: 'BCH-2026-007',
      purchase_price: 2900,
      initial_qty: 30,
      remaining_qty: 30,
      supplier_id: 'sup_distributor_snack',
      expiry_date: '2026-12-15',
      status: 'Aktif',
      created_at: now,
    },
    {
      id: 'btc_08_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_08',
      batch_number: 'BCH-2026-008',
      purchase_price: 7500,
      initial_qty: 12,
      remaining_qty: 12,
      supplier_id: 'sup_distributor_snack',
      expiry_date: '2026-10-30',
      status: 'Aktif',
      created_at: now,
    },
    {
      id: 'btc_09_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_09',
      batch_number: 'BCH-2026-009',
      purchase_price: 48000,
      initial_qty: 8,
      remaining_qty: 8,
      supplier_id: 'sup_konveksi_seragam',
      status: 'Aktif',
      created_at: now,
    },
    {
      id: 'btc_10_a',
      school_id: DEFAULT_SCHOOL_ID,
      product_id: 'prd_10',
      batch_number: 'BCH-2026-010',
      purchase_price: 17000,
      initial_qty: 15,
      remaining_qty: 15,
      supplier_id: 'sup_konveksi_seragam',
      status: 'Aktif',
      created_at: now,
    },
  ];
  await putMultipleToStore(STORES.PRODUCT_BATCHES, batches);

  // 10. Initial Stock Movements
  const movements: StockMovement[] = batches.map((b) => ({
    id: 'mov_init_' + b.id,
    school_id: DEFAULT_SCHOOL_ID,
    product_id: b.product_id,
    batch_id: b.id,
    movement_type: 'PURCHASE',
    qty: b.initial_qty,
    notes: 'Saldo stok awal sistem Koperasi Sekolah',
    user_id: 'usr_admin',
    user_name: 'Administrator',
    created_at: now,
  }));
  await putMultipleToStore(STORES.STOCK_MOVEMENTS, movements);

  // 11. Initial Open Cash Session so Kasir can immediately transact
  const initialSession: CashSession = {
    id: 'cs_' + today + '_001',
    school_id: DEFAULT_SCHOOL_ID,
    user_id: 'usr_kasir',
    user_name: 'Dewi Anggraini (Petugas Kasir)',
    open_time: now,
    initial_cash: 200000, // Rp 200.000 modal kembalian awal
    total_sales_cash: 0,
    total_in_cash: 0,
    total_out_cash: 0,
    expected_closing_cash: 200000,
    status: 'OPEN',
    created_at: now,
  };
  await putToStore(STORES.CASH_SESSIONS, initialSession);
}
